### ISSUE TITLE
USER01 - Define how to assign roles to users

### ISSUE THREAD

**Issue by gregoriopalama** [gdgpescara/hedwig#115]
Define which mechanism we should use.
We will use Firebase Auth for the authentication capability.
It uses custom claims. Should we use them? Or maybe we can rely on something else?

**Comment by camillobucciarelli** [comment]
I think that custom claims are a good choice for managing user roles in the Firebase ecosystem.

However, we can expose some Functions to handle specific use cases related to user management instead of using SDK directly in BFF to permit abstraction and segregation between Firebase SDK and application logic.

**Comment by gregoriopalama** [comment]
> However, we can expose some Functions to handle specific use cases related to user management instead of using SDK directly in BFF to permit abstraction and segregation between Firebase SDK and application logic.

That's the idea. For example, #131 allows to promote a user to the organizer role.

> I think that custom claims are a good choice for managing user roles in the Firebase ecosystem.

Great, that was my idea also.
I would go with something like this:

```
getAuth()
  .setCustomUserClaims(uid, { organizer: true })
  .then(() => { 
    ...
  });
```
with the role called `organizer`. I don't think we would need to use different roles, so, as for now, this will be the only possible claim.
Wdyt @camillobucciarelli ?

**Comment by camillobucciarelli** [comment]
> with the role called organizer. I don't think we would need to use different roles, so, as for now, this will be the only possible claim.

If needed we can add some other claims.

**Comment by gregoriopalama** [comment]
Sounds good to me. 

#127, #131, #133, #136 have been updated, with the required detail on the user custom claim. I'll close this.
