### ISSUE TITLE
INFRA11 - Define a budget for Performance score in Lighthouse check

### ISSUE THREAD

**Issue by gregoriopalama** [gdgpescara/hedwig#120]
Update the Lighthouse check. It should pass only if the budget has been reached. 
Define a budget for the Performance score. It should be a reasonable score, chosen to achieve business objectives but to not require too much effort during the development.

**Comment by gregoriopalama** [comment]
On this, I would prefere defining the metrics for the single Web Vitals. @irsooti I'll leave this evaluation to you

**Comment by irsooti** [comment]
Yes, I'd stick on core web vitals to not add too much constraints on this phase, we could optimize details post-production. 

So in this phase, as standard I'd stay on:
- LCP: 2500
- FID: 100
- CLS: 0.1

Also, I've found a tool that generated this JSON - the structure looks familiar to the config file you just set in the PR 

```json
[
  {
    "resourceSizes": [],
    "timings": [
      {
        "metric": "largest-contentful-paint",
        "budget": 2500
      },
      {
        "metric": "max-potential-fid",
        "budget": 100
      },
      {
        "metric": "cumulative-layout-shift",
        "budget": 0.1
      }
    ]
  }
]
```
