### ISSUE TITLE
BO01 - Create a layout for the BackOffice

### ISSUE THREAD

**Issue by gregoriopalama** [gdgpescara/hedwig#123]
Create the basic layout for the BackOffice.
It should have a side menu, with the link to every available configuration, and a main shared section that will show the selected configuration page. It should be possible to toggle the side menu, making it a floating sidebar with just the icons, that expands itself when the user hover on it. At the top-right of the page there should be informations about the logged in user, with the possibility to logout.

![BO-Layout](https://github.com/gdgpescara/hedwig/assets/11695605/f8d0cf2b-5324-47ac-b4ff-ee4d1b766eaf)

The mobile version should use an hamburger menu for the side menu.

**Comment by irsooti** [comment]
To start this task, we must have a validated UI. 
For the BO, a good starting point could be a wireframe (no need of high fidelity). 

We could develop using daisy ui default design system - in this way we don't depend up to the details but on the very generic stuff provided by the basic design system we want to extend in the nearest future.

@gregoriopalama do we should involve UI team for this maybe?

**Comment by gregoriopalama** [comment]
Closed by #170
