### ISSUE TITLE
USER02 - Allow a User to register and login to the application

### ISSUE THREAD

**Issue by gregoriopalama** [gdgpescara/hedwig#126]
Create the registration and login workflow in the public section.
We should use the provided Firebase Auth flow.

Depends on #116

**Comment by GiorgioCampea** [comment]
reference:
Firebase & Astro (Astro documentation)
https://docs.astro.build/en/guides/backend/google-firebase/
Firebase UI - WEB
https://github.com/firebase/firebaseui-web/blob/master/README.md
