### ISSUE TITLE
BO04 - Add an endpoint in the Users API to promote a User to the Organizer role

### ISSUE THREAD

**Issue by gregoriopalama** [gdgpescara/hedwig#131]
Add an endpoint in the Users API, mapped to
PUT /user/{uid}
In the body, it should expect the role of the user. 
If the Organizer role is present, the endpoint will add the role to the user.
If the Organizer role is not present, the endpoint will delete the role from the user, if present.

The endpoint should be allowed to Organizer users only: the user must have the user custom claim `{ organizer: true }`.

Depends on #129, #115 and #149.

**Comment by camillobucciarelli** [comment]
I think is better to have a specific endpoint for role management to permit caller filter (in this case I think only organizers can assign the organizer role to other users).

So, in this case we can have a specific API like the following:

- **method**: PATCH (or PUT)
- **endpoint**: /user/roles/{uid} 
- **grant**: the caller needs to be an organizer
- **payload**: role I would like to assign/remove

We can use PUT /user/{uid} to handle user information changes if needed.

wdyt @gregoriopalama ?

**Comment by gregoriopalama** [comment]
I'm not convinced.

If we want separate endpoints, then they should look like /user/{uid}/whatever, we should use PUT and anything on /user/{uid} should be prohibited. In this case, a DELETE would be needed to remove the role from a user.
If we want to rely on /user/{uid}, then I agree it would be better to use a PATCH instead of a PUT, and no DELETE would be needed. 
I think this would impact on the whole backend design, tho, so better choose a style from now and stick to it for any future endpoint.
