### ISSUE TITLE
INFRA15 - Add the first Organizer account using the seeding script

### ISSUE THREAD

**Issue by gregoriopalama** [gdgpescara/hedwig#136]
Add a step to the seeding script.
It should accept the informations about the Organizer account, create it and set the Organizer role: the user must have the user custom claim `{ organizer: true }`.

Depends on #115.

**Comment by camillobucciarelli** [comment]
@gregoriopalama  where do we want to put the seeding scripts in the project tree?

**Comment by gregoriopalama** [comment]
I would create a new folder, maybe called `scripts`. We can use it for the seeding and for other purposes. For now, seeding will be its only purpose. We can use models or services from functions, if we need them.
